GET http://localhost:3001/api/students
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6ImJsYXNpbyIsImlkIjoiNjY2ZmZmZmVhNzc3YjBmZmQwNzVjZDdmIiwiaWF0IjoxNzE4NjIxODQxfQ.gEM_6_sssEs1OHMUd8WouOXG3ivSxu22rOCTfStOFcE