POST http://localhost:3001/api/students/many
Content-Type: application/json

# {
    [
    {"first_name":"Aluino","last_name":"Segge","other_name":"Ermanno","gender":"Male","house":"Water","dob":"07/15/2013"},
    {"first_name":"Malva","last_name":"Birkenhead","other_name":"Ailyn","gender":"Female","house":"Fire","dob":"06/20/2020"},
    {"first_name":"Lucius","last_name":"Wadforth","other_name":"Kareem","gender":"Male","house":"Water","dob":"12/13/2010"},
    {"first_name":"Humfrid","last_name":"Antunes","other_name":"Delbert","gender":"Male","house":"Fire","dob":"03/30/2023"},
    {"first_name":"Leonanie","last_name":"Ambrodi","other_name":"Gus","gender":"Female","house":"Wind","dob":"04/16/2007"},
    {"first_name":"Paulita","last_name":"Durston","other_name":"Terrye","gender":"Female","house":"Fire","dob":"01/10/2017"},
    {"first_name":"Flint","last_name":"Layman","other_name":"Brocky","gender":"Male","house":"Water","dob":"12/15/2008"},
    {"first_name":"Kermie","last_name":"Kybert","other_name":"Norbie","gender":"Male","house":"Earth","dob":"06/12/2010"},
    {"first_name":"Raynor","last_name":"Writer","other_name":"Caddric","gender":"Male","house":"Fire","dob":"10/04/2019"},
    {"first_name":"Kylila","last_name":"Karppi","other_name":"Vally","gender":"Female","house":"Water","dob":"02/10/2015"},
    {"first_name":"Wilma","last_name":"Goathrop","other_name":"Gwyneth","gender":"Female","house":"Earth","dob":"06/30/2009"},
    {"first_name":"Sherwood","last_name":"De la Eglise","other_name":"Iago","gender":"Male","house":"Fire","dob":"03/08/2010"},
    {"first_name":"Cart","last_name":"Gillivrie","other_name":"Murvyn","gender":"Male","house":"Earth","dob":"10/28/2022"},
    {"first_name":"Emlyn","last_name":"Collum","other_name":"Annaliese","gender":"Female","house":"Earth","dob":"12/13/2013"},
    {"first_name":"Britta","last_name":"Adolf","other_name":"Claretta","gender":"Female","house":"Earth","dob":"12/27/2019"},
    {"first_name":"Kalli","last_name":"Gun","other_name":"Kim","gender":"Female","house":"Wind","dob":"08/18/2014"},
    {"first_name":"Andrus","last_name":"Iacovazzi","gender":"Male","house":"Water","dob":"01/17/2019"},
    {"first_name":"Marianna","last_name":"Smithson","other_name":"Mirella","gender":"Female","house":"Wind","dob":"02/25/2023"},
    {"first_name":"Eberto","last_name":"Farlamb","other_name":"Gram","gender":"Male","house":"Wind","dob":"05/27/2005"},
    {"first_name":"Sharona","last_name":"Domney","other_name":"Alica","gender":"Female","house":"Fire","dob":"11/07/2014"},
    {"first_name":"Penn","last_name":"Mockford","other_name":"Lauren","gender":"Male","house":"Earth","dob":"12/14/2021"},
    {"first_name":"Jorie","last_name":"Husset","other_name":"Noami","gender":"Female","house":"Fire","dob":"11/21/2008"},
    {"first_name":"Noellyn","last_name":"Beastall","other_name":"Lauren","gender":"Female","house":"Water","dob":"11/13/2006"},
    {"first_name":"Bobby","last_name":"Michell","gender":"Male","house":"Earth","dob":"01/21/2011"},
    {"first_name":"Roseanna","last_name":"Bourgourd","other_name":"Idette","gender":"Female","house":"Wind","dob":"09/16/2010"},
    {"first_name":"Mano","last_name":"Bigland","other_name":"Hercules","gender":"Male","house":"Fire","dob":"09/08/2011"},
    {"first_name":"Thain","last_name":"enzley","gender":"Male","house":"Earth","dob":"12/19/2006"},
    {"first_name":"Isis","last_name":"de Mullett","other_name":"Nollie","gender":"Female","house":"Wind","dob":"10/07/2011"},
    {"first_name":"Paco","last_name":"Lacasa","other_name":"Joe","gender":"Male","house":"Earth","dob":"11/08/2014"},
    {"first_name":"Teddi","last_name":"Springell","other_name":"Jaclyn","gender":"Female","house":"Fire","dob":"09/06/2010"},
    {"first_name":"Sidney","last_name":"Wilsher","other_name":"Zelig","gender":"Male","house":"Earth","dob":"01/18/2021"},
    {"first_name":"Putnam","last_name":"Feaks","gender":"Male","house":"Wind","dob":"02/02/2006"},
    {"first_name":"Domingo","last_name":"Prentice","other_name":"Desmund","gender":"Male","house":"Wind","dob":"05/21/2015"},
    {"first_name":"La verne","last_name":"McKie","other_name":"Roslyn","gender":"Female","house":"Water","dob":"06/15/2013"},
    {"first_name":"Pen","last_name":"Skeldon","other_name":"Veda","gender":"Female","house":"Wind","dob":"06/27/2020"},
    {"first_name":"Darelle","last_name":"Escalero","other_name":"Estelle","gender":"Female","house":"Fire","dob":"08/11/2011"},
    {"first_name":"Brenna","last_name":"Aishford","gender":"Female","house":"Water","dob":"03/14/2008"},
    {"first_name":"Joan","last_name":"Hargey","other_name":"Milly","gender":"Female","house":"Earth","dob":"04/29/2008"},
    {"first_name":"Calhoun","last_name":"Wildes","gender":"Male","house":"Wind","dob":"08/31/2009"},
    {"first_name":"Cirilo","last_name":"Lambis","other_name":"Konstantin","gender":"Male","house":"Wind","dob":"03/28/2021"},
    {"first_name":"Jimmie","last_name":"Yerrington","other_name":"Andreas","gender":"Male","house":"Fire","dob":"09/15/2014"},
    {"first_name":"Garvey","last_name":"Auckland","gender":"Male","house":"Fire","dob":"08/12/2019"},
    {"first_name":"Ibbie","last_name":"Brommage","other_name":"Gillan","gender":"Female","house":"Water","dob":"12/07/2010"},
    {"first_name":"Axel","last_name":"Zwicker","other_name":"Aldon","gender":"Male","house":"Earth","dob":"02/22/2009"},
    {"first_name":"Koenraad","last_name":"Brocklesby","other_name":"Chase","gender":"Male","house":"Earth","dob":"02/04/2009"},
    {"first_name":"Field","last_name":"Hissie","other_name":"Jarvis","gender":"Male","house":"Wind","dob":"09/15/2023"},
    {"first_name":"Garth","last_name":"Regina","other_name":"Hermy","gender":"Male","house":"Wind","dob":"09/30/2009"},
    {"first_name":"Powell","last_name":"Shears","other_name":"Lazare","gender":"Male","house":"Water","dob":"08/13/2020"},
    {"first_name":"Tanhya","last_name":"Handscombe","other_name":"Mickie","gender":"Female","house":"Earth","dob":"06/09/2021"},
    {"first_name":"Delmar","last_name":"Tuft","other_name":"Curry","gender":"Male","house":"Wind","dob":"05/27/2017"}]
