POST http://localhost:3001/api/students
Content-Type: application/json

{
   "first_name":"Mitchell",
   "last_name":"Nsimbi",
   "other_name":"Blasio",
   "dob":"12/04/2000",
   "house":"wind",
   "games_played":[
      {"game":"664e41038b131d61f7aad12c", "points":3}
   ]
   
}
