POST http://localhost:3001/api/students
Content-Type: application/json

{
    "first_name": "Rogers",
    "last_name": "Mukiibi",
    "other_name": "Timothy",
    "dob": "0208-06-30T21:32:44.000Z",
    "house": "Water"

  }