POST http://localhost:3001/gameplays
Content-Type: application/json

{
    "game":"66629960309d845f77fb784f",
    "players": [
        {
            "player":"665ecfd2cb67607a66d0b6d9",
            "position":1
        },
        {
            "player":"665ecf76cb67607a66d0b6cf",
            "position":4
        },
        {
            "player":"665ecf8dcb67607a66d0b6d1",
            "position":3
        },
        {
            "player":"665ecfb2cb67607a66d0b6d5",
            "position":2
        }
    ]
}