POST http://localhost:3001/api/gameplays
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6ImJsYXNpbyIsImlkIjoiNjY2ZmZmZmVhNzc3YjBmZmQwNzVjZDdmIiwiaWF0IjoxNzE4NjIxODQxfQ.gEM_6_sssEs1OHMUd8WouOXG3ivSxu22rOCTfStOFcE

# {
#     "game":"6671771a4192bd17072b7673",
#     "players": [
#         {
#             "player":"666ae4d56ca7bc36cd005986",
#             "position":null
#         },
#         {
#             "player":"666ae4d56ca7bc36cd005987",
#             "position":null
#         },
#         {
#             "player":"666ae4d56ca7bc36cd005988",
#             "position":null
#         },
#         {
#             "player":"666ae4d56ca7bc36cd005989",
#             "position":null
#         }
#     ]
# }
{
    "game":"6671771a4192bd17072b7673",
    "players": [
        {
            "player":"666ae4d56ca7bc36cd005986",
            "position":1
        },
        {
            "player":"666ae4d56ca7bc36cd005987",
            "position":2
        },
        {
            "player":"666ae4d56ca7bc36cd005988",
            "position":3
        },
        {
            "player":"666ae4d56ca7bc36cd005989",
            "position":4
        }
    ]
}